### ISSUE TITLE
Default Model didn't work

### ISSUE THREAD

**Issue by hassanmuhh** [timkmecl/codegpt#13]
First of all response is very slow it may takes about 1 min.

All of Models didn't work **expect** "code-davinci-002", which give me wrong answers.

**Comment by timkmecl** [comment]
If only `code-` models work, it may be because you do not have any credits on your OpenAI account (since only those models are free the others don't work in that case) - have you checked that? The correctness of the answers received is also based on the models, and to get the answers as good as possible it is unfortunately recommended to use the more powerful paid models.

As for the speed, it's completely up to OpenAI. They sometimes have too much traffic on their servers and consequently all the projects using it, including this extension, run slow.
